/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_screenconfig_free: (a: number, b: number) => void;
export const __wbg_enumerationsettings_free: (a: number, b: number) => void;
export const __wbg_fixeddomains_free: (a: number, b: number) => void;
export const start: () => void;
export const screen: (a: any, b: any) => any;
export const __wbgt__screening_wasm::screen_influenza: (a: number) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => [number, number];
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_wasmbindgentestcontext_free: (a: number, b: number) => void;
export const wasmbindgentestcontext_new: () => number;
export const wasmbindgentestcontext_include_ignored: (a: number, b: number) => void;
export const wasmbindgentestcontext_filtered_count: (a: number, b: number) => void;
export const wasmbindgentestcontext_run: (a: number, b: number, c: number) => any;
export const __wbgtest_console_log: (a: any) => void;
export const __wbgtest_console_debug: (a: any) => void;
export const __wbgtest_console_info: (a: any) => void;
export const __wbgtest_console_warn: (a: any) => void;
export const __wbgtest_console_error: (a: any) => void;
export const __wbgtest_cov_dump: () => [number, number];
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2b0c0863030af562: (a: number, b: number) => void;
export const closure1910_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures__invoke0_mut__h823fe21e0a7a9454: (a: number, b: number) => void;
export const closure1928_externref_shim: (a: number, b: number, c: any, d: number, e: any) => void;
export const closure1932_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
